version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ai-receptionist-db
    environment:
      POSTGRES_DB: ai_receptionist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: dev
    container_name: ai-receptionist-web
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ai_receptionist?schema=public
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # Python LiveKit Voice Agent (Primary)
  python-agent:
    build:
      context: ./python-agent
      dockerfile: Dockerfile
      target: dev
    container_name: ai-receptionist-python-agent
    depends_on:
      - web
    env_file:
      - .env
    environment:
      - BACKEND_API_URL=http://web:3000
    volumes:
      - ./python-agent:/app
    command: python voice_agent.py dev

  # Database Admin Interface (Optional)
  adminer:
    image: adminer
    container_name: ai-receptionist-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

volumes:
  postgres_data:
